# Generated by Django 3.2.5 on 2021-09-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='do_you_want_to_receive_grocerry_recommendations',
            new_name='are_you_above_18',
        ),
    ]
